import { z } from 'zod'

export const createDealSchema = z.object({
  accountId: z.union([z.string().min(1, 'Account is required'), z.number()]),
  accountName: z.string().min(1, 'Account name is required'),
  dealName: z.string().optional(),
  ticketId: z.union([z.string(), z.number()]).optional(),
  ticketNumber: z.union([z.string(), z.number()]).optional(),
  dealType: z.string().min(1, 'Deal type is required'),
  loanType: z.string().min(1, 'Loan type is required'),
  typeOfLogin: z.string().optional(),
  typeOfCaseLogin: z.string().optional(),
  ticketLogin: z.string().optional(),
  dealStage: z.string().min(1, 'Deal stage is required'),
  dealStatus: z.string().min(1, 'Deal status is required'),

  disbursedAmount: z.string().optional(),
  sanctionAmount: z.string().optional(),
  approvedAmount: z.string().optional(),
  amountRequired: z.string().min(1, 'Amount is required'),
  processingFees: z.string().optional(),
  dealStatusClosing: z.string().optional(),
  mmCharges: z.string().optional(),
  insuranceAmount: z.string().optional(),
  pfPercentage: z.string().optional(),
  rateOfInterest: z.string().optional(),
  interestType: z.string().optional(),

  dealCallBackDatetime: z.string().optional(),
  dealExpectedClosing: z.string().min(1, 'Expected closing date is required'),
  disbursementDate: z.string().optional(),
  lenderLoginDate: z.string().optional(),
  lenderLoginType: z.string().min(1, 'Lender login type is required'),
  loanStartDate: z.string().optional(),
  loanEndDate: z.string().optional(),
  targetedDisbursementDate: z.string().optional(),
  tenure: z.union([z.string(), z.number()]).optional(),

  lenderCode: z.string().optional(),
  lenderName: z.string().min(1, 'Lender name is required'),
  partnerName: z.string().min(1, 'Partner name is required'),
  customerRejectionReason: z.string().optional(),
  customerRejectionStatusExplanation: z.string().optional(),
  lenderRejectionReason: z.string().optional(),
  lenderRejectionStatusExplanation: z.string().optional(),
  partnerCode: z.string().optional(),
  paymentReceipt: z.string().optional(),
  potential: z.string().optional(),
  product: z.string().optional(),
})

export type CreateDealFormValues = z.infer<typeof createDealSchema>
